---
mysql_databases:
  - { name: demo }
  - { name: d7 }
  - { name: ck2 }
  - { name: commercedeploy }
  - { name: panelsverse }
  - { name: panopoly }
  - { name: commerce }
  - { name: media }
  - { name: drupal8 }
  - { name: mojocart }

apache_vhosts:
  - {servername: "drupal7.contrib.dev", documentroot: "/var/www/drupal7"}
  - {servername: "ck2.contrib.dev", documentroot: "/var/www/ck2"}
  - {servername: "commercedeploy.contrib.dev", documentroot: "/var/www/commercedeploy"}
  - {servername: "panelsverse.contrib.dev", documentroot: "/var/www/panelsverse"}
  - {servername: "panopoly.contrib.dev", documentroot: "/var/www/panopoly"}
  - {servername: "commerce.contrib.dev", documentroot: "/var/www/commerce"}
  - {servername: "media.contrib.dev", documentroot: "/var/www/media"}
  - {servername: "drupal8.contrib.dev", documentroot: "/var/www/drupal8"}
  - {servername: "mojocart.contrib.dev", documentroot: "/var/www/mojocart"}
