---
- hosts: contribdev
  gather_facts: yes

  vars_files:
    - config/main.yml
    - config/envs.yml

  pre_tasks:
    - name: Ensure apt is up to date.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.php-xdebug
    - mglaman.selenium
